### PR TITLE
Support for localized alert push notifications (title-loc-key, loc-key, title-loc-args etc)

### PR DESCRIPTION
**Pull request by btrappe**
Great project it helped me very much to shorten my dev time !
Beside the loc features I added SetToken function because I need to send a personalized message to a number of devices of the same user, thus it is convenient to prepare a push and then simple loop through the device token list.

### CODE REVIEW

**Comment by alexalok** [comment]
Hello Bernd, 

thank your for your work! Sorry for not reviewing it for so long. I still feel a bit conflicted about the `SetToken` method because I'd rather keep the `ApplePush` object non-reusable (that is, you create it with the specific parameters to the specific sender, you send it and then throw it away). As for your use-case, I think it's better to allow providing multiple push tokens to a single push. I've fired a separate [issue](https://github.com/alexalok/dotAPNS/issues/41) for that. 

If possible, could you extract the `SetToken`-related commit to another branch and leave only the localized alert related one in this pull request?

It would be perfect to have some tests as well, but I can write them myself if you don't have time for that currently.

**Comment by mtalaga** [comment]
Hi Alex, will this PR be merged sometime soon? I need to use loc-key and loc-args approach for sending push messages, and this would be useful for me. If not, is there any other way how can I achieve that without merging this PR?

**Comment by alexalok** [comment]
Hi, @mtalaga!

There are 2 issues preventing this PR from merging:
1. It introduces `SetToken` method, which is not related to the PR itself.
2. It lacks tests for the new `AddAlert` overload.

Unfortunately, I won't have time to work with that in the nearest future. If you feel brave, you can fork the repo and create a PR yourself.

**Comment by alexalok** [comment]
Superseded by #62.

**Pull request closed without merging**
